### ISSUE TITLE
Update conf.py and ci_cd.yml to use DOCUMENTATION_CNAME env variable

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#107]
🐞 **Problem**
Ideally, we should define key variables in one single place. As per @RobPasMue suggestion some time ago, let us use a variable named `DOCUMENTATION_CNAME` in our `ci_cd.yml` files to specify the value for the canonical name pointing to the documentation website. This value should be used for the `version.json` file too.

**Comment by RobPasMue** [comment]
With this issue do you just want to update the ``ci_cd.yml`` file of this repository? Or do you want to implement this logic within the actions and force all repositories to do it? Just asking 😄
