### ISSUE TITLE
Dropdown menu should take you to the equivalent vXXX page

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#122]
### 📝 Description of the feature

I think it will be nice if the dropdown takes you to the equivalent page in the previous/newer version.

For example if we are in `v2`` of ``examples.html`` and we select version ``v1``, it should take you to the version 1 of  ``examples.html``, not back to main. So we can compare changes in the API easier.

I think it should not be difficult to implement. I understand that a 404 error should be shown if that specific page didn't exist in the newly selected version.

**Comment by RobPasMue** [comment]
We might want to transfer this issue to the ``ansys-sphinx-theme`` repository 😄

**Comment by MaxJPRey** [comment]
This is an excellent idea for comparing APIs behavior and changes.

**Comment by germa89** [comment]
> We might want to transfer this issue to the `ansys-sphinx-theme` repository 😄

Someone wasn't really focused yesterday....XD

**Comment by RobPasMue** [comment]
> > We might want to transfer this issue to the `ansys-sphinx-theme` repository 😄
> 
> Someone wasn't really focused yesterday....XD

Hahaha! Transferring issue.. no biggie!

**Comment by RobPasMue** [comment]
I couldn't just transfer this issue - that's an org functionality only (meaning, I can only transfer issues to other repos inside the same org and with the same visibility). So... Had to create it manually: https://github.com/ansys/ansys-sphinx-theme/issues/175
