### ISSUE TITLE
Migrate all versioning logic to a Python script

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#134]
🐞 **Problem**
The [logic behind the doc-deploy-stable](https://github.com/pyansys/actions/blob/main/doc-deploy-stable/action.yml#L53-L86) for multi-version mixes between Shell and Python script.

I think it would make more sense to delegate all the logic in a Python script that:

* Performs the proper tag check
* Crops the version to X.Y numbers
* Applies all the version update logic

Note that this change does not affect the logic itself, so no breaking changes are introduced when implementing this.

**Comment by RobPasMue** [comment]
I totally agree yeah... better all this scripting to be in one place rather than multiple...

**Comment by MaxJPRey** [comment]
+1 for moving the logic in a Python script.

**Comment by jorgepiloto** [comment]
Closing this after #163. Everything is now in the form of a bash workflow.
