### ISSUE TITLE
Lack of consistency on paths for released artifacts

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#138]
The ``release-to-PyPI`` and ``release-to-Github`` are not consistent.

The PyPI action download the artifacts (all) to a folder called ``${{ inputs.library-name}}-artifacts`` but then, the ``release-to-github`` action check the folder ``other-artifacts``.

**Comment by jorgepiloto** [comment]
Thanks for pointing this out, @germa89. We should come with a common strategy for this. We could even use the `dist/` folder instead, as this is the place where artifacts are expected to be placed.

**Comment by RobPasMue** [comment]
Or we could just create an artifacts folder.. Not all artifacts are expected to be in the ``dist/`` folder AFAIK.

**Comment by jorgepiloto** [comment]
Sure, that works as long as we agree on unifying our actions.

**Comment by germa89** [comment]
If we are aiming to use all the pyansys actions together, there should be some agreement on output directories, file names, etc...
