### ISSUE TITLE
Implement ``dry-run`` option for critical actions

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#139]
Our actions should have a ``dry-run`` option for the important/only-can-do-once things... like release to PyPI.

**Comment by jorgepiloto** [comment]
Sounds good!

**Comment by RobPasMue** [comment]
Yeah, I agree! Let's go ahead with it

**Comment by germa89** [comment]
For PyPI, we use twine which does not have ``dry-run`` option.
There is a PR about that though: https://github.com/pypa/twine/issues/207
