### ISSUE TITLE
Allow to publish additional artifacts in release-github action

### ISSUE THREAD

**Issue by germa89** [pyansys/actions#140]
So far, the action uploads everything. I don't think this is a good approach. Everything should be optional.

```yml

    - name: "Release to GitHub"
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ inputs.library-name }}/*.whl
          ${{ inputs.library-name }}/*.tar.gz
          documentation-html.zip
          documentation-pdf.zip
          other-artifacts/**/*-wheelhouse-*.zip
```

**Comment by jorgepiloto** [comment]
Why not? A release has its own page in GitHub and should contain all generated artifacts for it. Even if artifacts got uploaded to the CI/CD, those will expire. Artifacts published in releases do not.

Also, I do not agree on making optional artifacts publishing. This means more variables and more variables lead to more inconsistency across our pipelines.

**Comment by jorgepiloto** [comment]
Pinging here @pyansys/pyansys-core for having more opinions about this.

**Comment by RobPasMue** [comment]
I must say that I agree with @jorgepiloto - Though flexibility is important, the whole goal of PyAnsys actions was to make a standard way of running our workflows. Such that we all reuse the same actions. Compromising is therefore something that we all must do throughout the PyAnsys ecosystem if we want to use them. Because not all the actions will always be just as we expected. And I also agree that the more optional arguments we provide, the more difficult it is to maintain and to understand what is happening in each workflow...

**Comment by germa89** [comment]
My two cents on this.

I understand we want to enforce good-common practices across pyansys by making them to use these actions. But each project is different. I think not all the projects will have PDF docs, or HTML to upload. But they might have other files. I think having 'whl' and 'tag.gz' files uploaded is something that should be mandatory. I do not think the same about docs or other files.

**Comment by RobPasMue** [comment]
PDF, HTML and JSON for docs is "mandatory". The need of having a PDF for the docs is enforced by customers that do not have an open internet connection and thus require a file for looking into the docs. Same happens for the wheels.

JSON is needed for the dev-portal. HTML, is obvious of course - it's the way we publish our docs. So, in general, they should be enforced.

**Comment by germa89** [comment]
> PDF, HTML and JSON for docs is "mandatory". The need of having a PDF for the docs is enforced by customers that do not have an open internet connection and thus require a file for looking into the docs. Same happens for the wheels.
> 
> JSON is needed for the dev-portal. HTML, is obvious of course - it's the way we publish our docs. So, in general, they should be enforced.

Fair enough. Still we should be able to add other artefacts if we wish.

**Comment by RobPasMue** [comment]
Agreed, adding additional ones should be possible. But the basic,common,mandatory ones should be named the same

**Comment by jorgepiloto** [comment]
Renaming this issue.

**Comment by germa89** [comment]
> Agreed, adding additional ones should be possible. But the basic,common,mandatory ones should be named the same

We did comment yesterday about the possibility to use arguments for such names/paths. So we are not forced to use specific names/paths. What was the final consent in that regards?

**Comment by RobPasMue** [comment]
I think it was more oriented to "additional" artifacts that you wanted to upload. But the main ones should still be named homogeneously throughout the ecosystem IMO
