### ISSUE TITLE
Add skip json build option for docs build.

### ISSUE THREAD

**Issue by Revathyvenugopal162** [pyansys/actions#145]
Update the  doc-build action with option for skipping the JSON build in favor of updating the theme to pydata-0.12.0.

Adding xml build can also be an option.

**Comment by RobPasMue** [comment]
I think we should conceive it the other way around. We skip it by default, and if somebody wants the JSON build, then you have to configure it. Pinging @jorgepiloto and @MaxJPRey for insights.

**Comment by Revathyvenugopal162** [comment]
I agree, implementation required is like that (skip it by default), as no other libs requires json docs, other than for dev portal **for the moment**.  **_Also xml build required or not (at present) has to be decide._**

**Comment by RobPasMue** [comment]
Let's try to be as simple as possible with our PRs... This issue's title is: **Add skip json build option for docs build**... Let's stick to what we ask for and not do 4 things in one same PR =)

XML build depends on whether the dev portal can ingest XML files or not. It's not up to us to make the call. This has to be evaluated with them.

**Comment by jorgepiloto** [comment]
Let us add the `skip_json_build=true` option. Also, no need to worry about `XML` builder.
