### ISSUE TITLE
Use right compression tool to decompress documentation artifacts

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#148]
🐞 **Problem**
As pointed out by @AlejandroFernandezLuces, the right decompression tool should be used according to the type of compression software.

Right now, only ZIP extensions are supported. Let us target to TAR extensions too.

**Comment by MaxJPRey** [comment]
@jorgepiloto Would this be an option available for users?

**Comment by jorgepiloto** [comment]
As implemented in #149, using [ouch](https://github.com/ouch-org/ouch) avoids the need to specify the file type of the compressed artifact.
