### ISSUE TITLE
Add action validation in GH CI/CD

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#15]
### 📝 Description of the feature

Don't know if it is possible, just thinking here, but... it would definitely be useful to have a way of testing the actions before committing them. Against a dummy repo extracted from ansys-templates or similar. What do you think @jorgepiloto? I can investigate as well.

**Comment by jorgepiloto** [comment]
I agree, this is something we need to explore.

The documentation deploy and release actions are the non-trivial ones. They expect a `gh-pages` branch and a repository to be published to.

**Comment by RobPasMue** [comment]
Yeah, not saying it is straightforward to test them. But we should try to figure something out. Planning on investigating it for next week on my side =)

**Comment by jorgepiloto** [comment]
Solved in #38. Closing.
