### ISSUE TITLE
Add a `/` at the end of every URL in the versions.json file to allow switching between version pages  

### ISSUE THREAD

**Issue by Revathyvenugopal162** [pyansys/actions#151]
Update the url in script in the for `{cname}/dev/` and `{cname}/release/{version}/` from `{cname}/release/{version}` to get use of the feature  **_Dropdown menu should take you to the equivalent vXXX page_** posted in the issue https://github.com/ansys/ansys-sphinx-theme/issues/175  posted by @RobPasMue in ansys-sphinx-theme. See https://github.com/ansys/ansys-sphinx-theme/blob/gh-pages/release/versions.json (updated manually according to the requirement this morning) for the format and https://sphinxdocs.ansys.com/dev/getting_started/index.html to explore the feature.

i am not sure, this should fix manually for all those repos in which the multidoc feature has been already implemented. Pinging @jorgepiloto for insights.

**Comment by jorgepiloto** [comment]
I think this feature is automatically inherited once we upgrade to the latest pydata-sphinx-theme. Do you know if this is the expected behavior, @RobPasMue? If so, we only need to care about upgrading our ansys-sphinx-theme and the logic in PyData will take care of the rest.

**Comment by jorgepiloto** [comment]
I can confirm that by upgrading to pydata-sphinx-theme, this will be the default behaviour. No need to modify anything in our side.

PyData Sphinx theme JSON file: https://github.com/pydata/pydata-sphinx-theme/blob/main/docs/_static/switcher.json

**Comment by jorgepiloto** [comment]
After a private discussion this got much clear.
