### ISSUE TITLE
Documentation crawlers going crazy with ``release`` folder approach

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#154]
After a private discussion with @akaszynski, we should reconsider our ``dev`` and  ``release`` folder strategy. Search engine crawlers are going crazy and not counting the hits properly due to this issue. Our main index file is always pointing to the latest "release" folder but this folder may be very "dynamic" in naming - depending on the frequency on which a package releases a minor version...

We should try to make it more stable.. I propose the following scheme:
* ``dev``: as it is right now.
* ``stable``: for the latest released version.
* ``releases``: for older releases.

That ways crawlers always know to look at ``https://CNAME/stable/index.html``

Pinging @jorgepiloto and @Revathyvenugopal162 for visibility and discussion. Also pinging the rest of the @pyansys/pyansys-core team.

**Comment by germa89** [comment]
My question is.....

How?
<img src="https://media2.giphy.com/media/n5NtisNKVzXWg/giphy.gif"/>

How did you realize the crawlers were going crazy??

**Comment by RobPasMue** [comment]
> My question is.....
> 
> ## How?
> ![](https://camo.githubusercontent.com/a68bb3aa842c8660fae4d26c2eb0b80806c8c82733e765e47f17393865991129/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4c705233523676476e37786e4a67736557792f67697068792e676966) [ ![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4c705233523676476e37786e4a67736557792f67697068792e676966](https://camo.githubusercontent.com/a68bb3aa842c8660fae4d26c2eb0b80806c8c82733e765e47f17393865991129/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4c705233523676476e37786e4a67736557792f67697068792e676966) ](https://camo.githubusercontent.com/a68bb3aa842c8660fae4d26c2eb0b80806c8c82733e765e47f17393865991129/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4c705233523676476e37786e4a67736557792f67697068792e676966) [ ](https://camo.githubusercontent.com/a68bb3aa842c8660fae4d26c2eb0b80806c8c82733e765e47f17393865991129/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f4c705233523676476e37786e4a67736557792f67697068792e676966)
> 
> How did you realize the crawlers were going crazy??

Google's search results are not as good as before 😄
