### ISSUE TITLE
Review input variables naming and order

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#169]
💡 **Idea**
Before the next stable release, let us make a heavy review on input variables naming and their order. The rules should be:

* Use `name-of-input-variable`. This is the same GitHub uses for keywords like `runs-on`, `cancel-in-progress`...
* First declared parameters should be the required ones followed by optional ones. Suggested by @RobPasMue.

**Comment by RobPasMue** [comment]
Thanks @jorgepiloto! Really appreciated
