### ISSUE TITLE
Enhance descriptions and job steps information

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#171]
💡 **Idea**
It is possible to benefit from the following YML syntaxt to create a multi-line comment:

```yml
key: >
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
  Fusce vulputate vehicula condimentum. Nulla eleifend mauris
  ut elementum posuere. Vestibulum egestas enim sit amet odio
  molestie, sed vehicula tellus tempor.
```

Let us apply it in the parameters names and descriptions. Also, let us investigate how this issue can also solve for #142.

**Comment by RobPasMue** [comment]
Awesome! That way we won't have such long lines :)
