### ISSUE TITLE
Consider deprecating the "doc-deploy-to-repo" action

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#175]
💡 **Idea**
The `doc-deploy-dev` and `doc-deploy-stable` allow now to deploy to an external repository. Hence, I would like to raise the questions: should we keep maintaining the `doc-deploy-to-repo` action?

**Comment by RobPasMue** [comment]
Nope... I'd delete it

**Comment by RobPasMue** [comment]
Plus, I think almost all (if not all) projects are now using the multiversioning scheme. So, it's not longer necessary.

**Comment by jorgepiloto** [comment]
Sounds good!
