### ISSUE TITLE
Package cleaning: add option to keep containers newer than a certain age

### ISSUE THREAD

**Issue by greschd** [pyansys/actions#177]
### 📝 Description of the feature

Currently, the package cleaning actions delete _all_ packages which do not meet the label criteria. It would be useful to have an option to keep e.g. packages that are newer than a specified number of days.

This gives time to react in case a new container is broken, and helps pinpoint the breaking change.

**Comment by RobPasMue** [comment]
Thanks @greschd! Adding it to the bucket list =)
