### ISSUE TITLE
Allow PDF to be optional in actions/release-github

### ISSUE THREAD

**Issue by iboyd-ansys** [pyansys/actions#178]
### 📝 Description of the feature

In my project PDF doc builds fail, for reasons that no one has been able to understand. It has not been considered critical because the primary documentation is HTML and this is fine. However, the lack of PDF doc causes the `release-github` action to fail.

It would be useful to allow PDF to be optional, to reflect that it is a secondary requirement.

### 💡 Steps for implementing the feature

Add a new optional input, boolean valued with default `true`, that specifies whether PDF is expected to be included in the release.

Adjust the logic of the steps to account for the flag.

**Comment by jorgepiloto** [comment]
Hi @iboyd-ansys, thanks for opening this issue.

The philosophy for `pyansys/actions` is very strict about existant artifacts and their naming. When we implemented the `release-github` action, we imposed the following criteria:

* Always deploy `wheels` and `sdist` artifacts
* Always deploy `documentation-html`
* Always deploy `documentation-pdf`
* Always deploy `wheelhouse`
* Allow to deploy any additional artifacts

**If a Python library can not generate this set of artifacts, it means there is some issue on their side. This forces us to go and explore such issue.**

Hence, I am closing this request.

However, let's work on solving this issue on your side.
