### ISSUE TITLE
Add ability to disable building pdf on `doc-build`

### ISSUE THREAD

**Issue by akaszynski** [pyansys/actions#204]
`doc-build-action` needs an option to not build the pdf. It's not always necessary and sometimes a pain to setup.

https://actions.docs.pyansys.com/version/stable/doc-actions/index.html#doc-build-action

**Comment by RobPasMue** [comment]
This has been discussed in #178... We shouldn't allow people to skip PDF builds. It is part of our "standards" to deliver a PDF as part of the release process. The only way we ensure that the PDF is generated is by forcing its build in the docs action. Making it optional would allow people not to align to standards, and make it more complicated to solve before releasing... I have to disagree with this issue and PR.

We know it's doable but the solution is not "taking the shortcut". We are happy to help anybody that has issues in their docs build. But the docs should be generated as a PDF.

PyAnsys actions are a way of ensuring some common standards across PyAnsys projects. We should allow as little shortcuts as possible...

**Comment by akaszynski** [comment]
That's ok. I'll be pinging you for help.

**Comment by jorgepiloto** [comment]
We are afraid that this option leads to the bad practice of not generating PDF documentation at all. The `pyansys/actions` are very strict in this sense.

**Comment by RobPasMue** [comment]
Yep, problem solved after talking to @akaszynski. Closing issue and PR.
