### ISSUE TITLE
release-github does not include whl and source files

### ISSUE THREAD

**Issue by ludovicsteinbach** [pyansys/actions#213]
Using v4.
It looks like the final step tries to publish the files 
```
# Include wheel and source distribution artifacts
dist/${{ inputs.library-name }}-artifacts/*.whl
dist/${{ inputs.library-name }}-artifacts/*.tar.gz
```

but the files were never placed in dist/.

**Comment by ludovicsteinbach** [comment]
It looks like the step to zip the pdf artifact is misconfigured: the path does not match the path at which artifacts were downloaded

**Comment by RobPasMue** [comment]
Opened a PR to solve this issue. Thanks for pointing it out @ludovicsteinbach!

**Comment by RobPasMue** [comment]
We just did a new release @ludovicsteinbach - could you try it out now? Let us know if there is something not working.

**Comment by ludovicsteinbach** [comment]
Yep works fine, pdf docs and source files were included the release, thanks @RobPasMue
