### ISSUE TITLE
Documentation versioning is not working properly

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#51]
If I go to the docs and click on the dropdown menu for the documentation versions available I get this:

![image](https://user-images.githubusercontent.com/37798125/201290641-e54b66ba-3dd0-4628-8463-ba00e8939718.png)

Which is perfect. But if I click on the ``dev`` element of the dropdown list, it redirects me to the ansys-templates documentation.

![image](https://user-images.githubusercontent.com/37798125/201290747-2937f250-0826-4f06-a509-03a120e253fd.png)

It looks like the mech has not been fully adapted.

**Comment by jorgepiloto** [comment]
Thanks for opening this, @RobPasMue.

My fault. I used the wrong CNAME when creating the `versions.json` file in the `gh-branch`. This cannot be fixed through a pull-request but through a commit. Here it is d7fa869.

**Comment by RobPasMue** [comment]
Great, thanks for solving it @jorgepiloto!
