### ISSUE TITLE
Adding target (as optional argument) to build-wheel action

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/actions#74]
Although one typically builds the wheel of a project by pointing at its necessary dependencies, one could also build a wheel of a package taking into account optional dependencies. For example:

**Default (typical) case:**
```bash
pip wheel . -w wheelhouse
```
**Wheel with optional targets:**
```bash
pip wheel .[my-target] -w wheelhouse
```

This use-case is specially interesting for the ``pyansys`` metapackage, since we are interested in generating the wheels of the ``all`` target - that is, all PyAnsys packages inside it.

Consider adding it and bumping version. I will be implementing it shortly. This argument should definitely be optional - since it is not the typical use case.

**Comment by MaxJPRey** [comment]
Sounds great @RobPasMue .

**Comment by RobPasMue** [comment]
This was solved after several attempts in the end... Look at https://github.com/pyansys/actions/blob/main/build-wheelhouse/action.yml for final solution
