### ISSUE TITLE
Investigate bug in versioning

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#76]
🐞 **Problem**
The multi-versioning seemed to work properly. However, the latest patch releases created a "1.1 (stable)", see https://actions.docs.pyansys.com/release/1.1/.

We need to investigate what happened here by taking a closer look to the CI/CD logs.

**Comment by RobPasMue** [comment]
Oh that's weird... You want me to look at it @jorgepiloto?

**Comment by jorgepiloto** [comment]
It looks like the shell script is working as expected as per CI/CD logs of v1.0.6, see https://github.com/pyansys/actions/actions/runs/3516024428/jobs/5892111781#step:2:979

**Comment by jorgepiloto** [comment]
Maybe this is a bug within the Python script... However, I do not understand when the `release/1.1/` gets created. The value for the `$folder` variable is `release/1.0`, which is the expected one for a tag with value `v1.0.6`.

**Comment by RobPasMue** [comment]
What happens if we create a tag named v1? Maybe it's caused because of that?

**Comment by jorgepiloto** [comment]
Oh! I see... You were on the right path, @RobPasMue: https://github.com/pyansys/actions/actions/runs/3516024402/jobs/5892115142#step:2:867

**Comment by jorgepiloto** [comment]
It looks like when a `v1` tag is created, somehow the shell script logic creates a `1.1` version...

**Comment by RobPasMue** [comment]
Yeah... we should definitely do something about that 😄

**Comment by jorgepiloto** [comment]
Let us check for the length of the version after removing the `v` and `release` prefixes.

We can adapt the workflow according the the length of the version, executing the deployment only for `X.Y.Z` versions.

**Comment by RobPasMue** [comment]
Sounds good to me! Thanks @jorgepiloto

**Comment by RobPasMue** [comment]
Working on it :)
