### ISSUE TITLE
Use cache-apt-packages in doc-build action

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#77]
🐞 **Problem**
During the last days, some actions for building documentation have increased its required time to complete. Although the reason is not clear, it may be related with system dependencies updates.

I am suspecting about LaTeX, as this is the heaviest dependency required to generate PDF documentation.

For this reason, let us take advantage of https://github.com/marketplace/actions/cache-apt-packages.

**Comment by RobPasMue** [comment]
This is interesting at least for the docs build. Want me to work on that @jorgepiloto?

**Comment by RobPasMue** [comment]
Even if not critical this will definitely be useful - at least for docs build. Let me get started.
