### ISSUE TITLE
Add more examples on how to use the actions

### ISSUE THREAD

**Issue by jorgepiloto** [pyansys/actions#82]
🐞 **Problem**
So far, each one of the actions contains a small gist explaining how to use it. These examples are quite trivial, containing only one step.

However, most of the projects within PyAnsys require to install a server to access all the logic through the Python library. How to combine this step with the pyansys/actions is not explained, even though it is a simple task.

💡 **Idea**
~We could create a `Examples` section showing more complex jobs or add more examples next to each one of the actions.~

Let us collect all the examples under each action, as similar to what we do with docstring examples. I am proposing this because some of the examples may not show all the possible inputs an action can take.

**Comment by jorgepiloto** [comment]
This idea came to me after discussing with @GuillemBarroso how to combine pyansys actions with dpf actions.

**Comment by MaxJPRey** [comment]
That is an excellent idea @jorgepiloto and @GuillemBarroso . It will help all the teams for sure.

**Comment by RobPasMue** [comment]
The specially critical one is the testing and documentation actions. Those are typically dependent on running a server... It's going to be difficult to sample this behaviour on a standalone repo (like the dev docs, sphinx theme etc). We need a server-based project (PyMAPDL, PyFluent, PyAEDT, PyGeometry... ).

**Comment by RobPasMue** [comment]
Ha! You're totally right @jorgepiloto! Let's do that!
